services:
  - type: web
    name: bnb-trading-bot
    runtime: python
    plan: free
    buildCommand: pip install --no-cache-dir -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 1 --timeout 30 server:app
    envVars:
      - key: BINANCE_API_KEY
        sync: false
      - key: BINANCE_API_SECRET
        sync: false
      - key: TEST_MODE
        value: "false"
      - key: PYTHONUNBUFFERED
        value: "1"
    healthCheckPath: "/health"
    autoDeploy: true
