services:
  - type: worker
    name: ltc-trading-bot
    runtime: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install --only-binary=all -r requirements.txt
    startCommand: python app/bot.py
    envVars:
      - key: BINANCE_API_KEY
        sync: false
      - key: BINANCE_API_SECRET
        sync: false
      - key: PYTHON_VERSION
        value: "3.11.10"
      - key: TEST_MODE
        value: "false"
      - key: PIP_PREFER_BINARY
        value: "1"
      - key: PIP_ONLY_BINARY
        value: ":all:"
    autoDeploy: false  # Ручной деплой для безопасности
