services:
  - type: worker
    name: ltc-trading-bot
    runtime: python
    plan: free
    buildCommand: |
      python -m pip install --upgrade pip setuptools wheel
      pip install --only-binary=all --prefer-binary -r requirements-simple.txt
    startCommand: python app/bot_simple.py
    envVars:
      - key: BINANCE_API_KEY
        sync: false
      - key: BINANCE_API_SECRET
        sync: false
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: TEST_MODE
        value: "false"
      - key: PIP_PREFER_BINARY
        value: "1"
      - key: PIP_ONLY_BINARY
        value: ":all:"
    autoDeploy: false  # Ручной деплой для безопасности
